name: React CI

on:
  push:
    branches:
      - "main"

jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          mkdir ./test
      - name: Deploy source-code
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.EC2_SSH_KEY }}
        with:
          source: "/test.txt"
          target: "/home/node_deploy"
          strip_components: 1

# jobs:
#   deploy:
#     name: "Deploy to staging"
#     runs-on: ubuntu-latest
#     steps:
#       - name: Configure SSH
#         run: |
#           mkdir -p ~/.ssh/
#           echo "$SSH_KEY" > ~/.ssh/staging.key
#           chmod 600 ~/.ssh/staging.key
#           cat >>~/.ssh/config <<END
#           Host staging
#             HostName $SSH_HOST
#             User $SSH_USER
#             IdentityFile ~/.ssh/staging.key
#             StrictHostKeyChecking no
#           END
#         env:
#           SSH_USER: ${{ secrets.USERNAME }}
#           SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
#           SSH_HOST: ${{ secrets.HOST_DNS }}

#       - name: Make empty file
#         run: ssh staging 'cd /home/react/react_elmo_admin && touch sample.js'

#       - name: Git Hard Reset
#         run: ssh staging 'cd /home/react/react_elmo_admin && git reset --hard origin/main'

#       # - name: Commit the local files
#       #   run: ssh staging 'cd /home/react/react_elmo_admin && git add . && git commit -m "Local Commits"'
      
      
#       - name: Git pull recent files
#         run: ssh staging 'cd /home/react/react_elmo_admin && git pull origin main'

#       - name: Delete empty file
#         run: ssh staging 'cd /home/react/react_elmo_admin && rm -rf sample.js'

#       - name: Install NPM Packages
#         run: ssh staging 'cd /home/react/react_elmo_admin &&  npm i'

#       - name: Create a Build
#         run: ssh staging 'cd /home/react/react_elmo_admin && NODE_OPTIONS="--max_old_space_size=4096 --openssl-legacy-provider" npm run build'
      
#       - name: Delete the existing build
#         run: ssh staging 'sudo rm -rf /home/elmo_admin/build'

#       - name: Move build to deploy folder
#         run: ssh staging 'sudo mv /home/react/react_elmo_admin/build /home/elmo_admin/build'

#       - name: Restart the server
#         run: ssh staging 'cd /home/elmo_admin && pm2 restart 1'

#       - name: send telegram message on push
#         uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: |
#             ${{ github.actor }} created commit:

#             Commit message: ${{ github.event.commits[0].message }}
            
#             Repository: ${{ github.repository }}
            
#             See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

#             Deployed Successfully.

#             Please check the changes in below link

#             http://65.2.65.214:3001
